/**
 * lib/types.ts — shared domain types, API contracts, and UI state interfaces.
 * Source of truth: ARCHITECTURE.md §2 (API contracts), §3 (error codes), §4 (reducer actions).
 * Types plus const lookup tables that are themselves data contracts (§3, §2.1 role union), plus
 * pure normalizers for untrusted wire input.
 * No runtime behaviour beyond those pure functions, no I/O — see lib/github.ts, lib/repoSummary.ts,
 * lib/mermaidSanitize.ts.
 */

/* ------------------------------------------------------------------ *
 * §2.1 — Domain: repo ingestion
 * ------------------------------------------------------------------ */

/** Role vocabulary for architecture nodes (ARCHITECTURE.md §2.1). */
export type ArchitectureRole =
  | "frontend"
  | "api"
  | "database"
  | "queue"
  | "cache"
  | "worker"
  | "config"
  | "unknown";

/** Runtime mirror of ArchitectureRole — needed to validate untrusted LLM output (RULES.md §3). */
export const ARCHITECTURE_ROLES: readonly ArchitectureRole[] = [
  "frontend",
  "api",
  "database",
  "queue",
  "cache",
  "worker",
  "config",
  "unknown",
] as const;

/** One node of the generated architecture diagram (ARCHITECTURE.md §2.1). */
export interface ArchitectureNode {
  id: string;
  label: string;
  role: ArchitectureRole;
  evidence: string;
}

/**
 * Capped, LLM-ready digest of the target repo (ARCHITECTURE.md §1.3–§1.4).
 * Every field is subject to the size caps in §1.4 — the caps are enforced by the producers,
 * not by these types, but no field here may be widened to carry raw file blobs (BOB.md §3.3).
 */
export interface RepoSummary {
  name: string;
  description: string | null;
  language: string | null;
  /**
   * The repo's own source folders, depth 1–3 — `src`, `src/components`, `packages/web/src` —
   * ranked by descendant file count (ties alphabetical), capped at ≤24.
   *
   * This is the field the /api/analyze prompt draws its node labels from: the diagram is meant to
   * be the repository's actual structure, so the model may label a node only with one of these
   * paths and may never invent a module the digest does not show.
   */
  moduleFolders: string[];
  /** Top 10 extensions by count. */
  fileCountByExt: Record<string, number>;
  hasDocker: boolean;
  /** ≤15 service names (docker-compose only, regex-extracted). */
  services: string[];
  /** ≤20 package names combined, `dependencies` prioritised over `devDependencies`. */
  dependencies: string[];
  /** First 800 chars after image/badge stripping, or null if no README. */
  readmeExcerpt: string | null;
  /** True if the GitHub tree response reported `truncated: true` (§1.2 step 2). */
  truncated: boolean;
}

/* ------------------------------------------------------------------ *
 * §2.1 — Domain: verdict (optional enrichment)
 * ------------------------------------------------------------------ */

export type FrictionLevel = "low" | "moderate" | "high";

export const FRICTION_LEVELS: readonly FrictionLevel[] = [
  "low",
  "moderate",
  "high",
] as const;

/**
 * Optional badge generated by the same LLM call as mermaidCode/architecture (§2.1).
 * Consumers MUST treat a missing value, or a `friction` outside FrictionLevel, as `null`
 * and render no badge — never as a `parse_failed` for the whole response (§2.1, Phase 2.6).
 */
export interface Verdict {
  friction: FrictionLevel;
  /** Badge caption, capped at ~160 chars server-side. Grounded only in the same RepoSummary (§2.1). */
  reason: string;
}

/* ------------------------------------------------------------------ *
 * §3 — Error codes
 * ------------------------------------------------------------------ */

export type ErrorCode =
  | "invalid_url"
  | "not_found"
  | "rate_limited"
  | "parse_failed"
  | "timeout"
  | "unknown";

/** §3 — client maps each code to exactly one user-facing string. Never forward raw upstream bodies. */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  invalid_url: "That doesn't look like a valid GitHub repo URL.",
  not_found: "Repo not found — check the URL or make sure it's public.",
  rate_limited: "GitHub rate limit hit — wait a minute and try again.",
  parse_failed: "Something went wrong reading that repo's structure. Try again.",
  timeout: "That took too long — the repo might be very large. Try again.",
  unknown: "Something went wrong. Try again.",
};

/** Error codes reachable from the two GitHub-free routes (§2.2, §2.3). */
export type LlmErrorCode = Extract<ErrorCode, "parse_failed" | "timeout" | "unknown">;

/* ------------------------------------------------------------------ *
 * §2 — Transport envelope
 * ------------------------------------------------------------------ */

export type ApiSuccess<T> = { data: T; error?: undefined };
export type ApiFailure = { data?: undefined; error: ErrorCode };
export type ApiFailureLlm = { data?: undefined; error: LlmErrorCode };

/**
 * All routes respond `{ data }` on success, `{ error }` on failure (§2.1–§2.3).
 * The optional-`undefined` form keeps `if (res.error) ... else res.data` narrowing safe under strict mode.
 */
export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

/* ------------------------------------------------------------------ *
 * §2.1 — POST /api/analyze
 * ------------------------------------------------------------------ */

export interface AnalyzeRequest {
  owner: string;
  repo: string;
}

export interface AnalyzeResult {
  repoSummary: RepoSummary;
  mermaidCode: string;
  architecture: ArchitectureNode[];
  verdict: Verdict | null;
}

export type AnalyzeResponse = ApiResponse<AnalyzeResult>;

/* ------------------------------------------------------------------ *
 * §2.2 — POST /api/analogy
 * ------------------------------------------------------------------ */

/**
 * The four built-in themes. Each has a hand-authored ROLE_VOCAB map in lib/analogyPrompts.ts,
 * which is what makes their analogies sharper than a one-shot prompt can manage.
 */
export type PresetAnalogyType = "restaurant" | "airport" | "hospital" | "city";

/**
 * Any analogy theme: one of the presets, or a free-text theme the user typed in themselves
 * (e.g. "Star Wars", "Cooking Show"). The `& {}` branch keeps editor autocomplete for the
 * presets while still accepting arbitrary strings — a bare `string` would lose the hints,
 * and a closed union would make custom themes impossible.
 */
export type AnalogyType = PresetAnalogyType | (string & {});

/** Runtime mirror of the preset themes — drives the AnalogySelector buttons (§2.2). */
export const ANALOGY_TYPES: readonly PresetAnalogyType[] = [
  "restaurant",
  "airport",
  "hospital",
  "city",
] as const;

/** PRD.md §2.5 — the theme auto-fired immediately after analyze success. */
export const DEFAULT_ANALOGY_TYPE: PresetAnalogyType = "restaurant";

/** Upper bound on a user-supplied theme string. Long enough for "90s Saturday Morning Cartoon". */
export const MAX_ANALOGY_TYPE_LENGTH = 40;

/** Narrowing helper — true only for the four built-in themes. */
export function isPresetAnalogyType(value: string): value is PresetAnalogyType {
  return ANALOGY_TYPES.indexOf(value as PresetAnalogyType) !== -1;
}

/**
 * Normalizes an untrusted analogyType off the wire into something safe to interpolate into a
 * prompt: trimmed, whitespace-collapsed, stripped of anything outside `[A-Za-z0-9 -]`, and
 * capped at MAX_ANALOGY_TYPE_LENGTH. Returns null when nothing usable survives.
 *
 * Both routes that accept an analogyType (and both prompts that embed it) rely on this being
 * the single gate — the theme string is free user text reaching an LLM, so it is sanitized
 * exactly like every other untrusted field.
 */
export function normalizeAnalogyType(raw: unknown): AnalogyType | null {
  if (typeof raw !== "string") return null;
  const cleaned = raw
    .replace(/[^A-Za-z0-9 -]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, MAX_ANALOGY_TYPE_LENGTH)
    .trim();
  return cleaned === "" ? null : cleaned;
}

/** One component→analogy vocabulary row (§2.2 mapping[]). */
export interface AnalogyMappingEntry {
  componentLabel: string;
  analogyRole: string;
  explanation: string;
}

/**
 * §2.2 labelMappings[] — the theme's short name for each diagram node, keyed by node id.
 *
 * Still part of the §2.2 response contract and still validated by /api/analogy, but no longer drawn
 * onto the diagram: the "Dynamic Diagram Label Morphing" mode that consumed it is retired
 * (ARCHITECTURE.md §5.1). The hover tooltip reads `mapping[].analogyRole` instead and touches no
 * SVG text (RULES.md §1).
 */
export interface LabelMapping {
  nodeId: string;
  /**
   * Prompt-generated free text, treated as untrusted: must pass the full RULES.md §1 pipeline
   * before being spliced into a diagram string. Missing ids fall back to the node's technical label.
   */
  analogyLabel: string;
}

export interface AnalogyRequest {
  architecture: ArchitectureNode[];
  analogyType: AnalogyType;
}

export interface AnalogyResult {
  analogyType: AnalogyType;
  mapping: AnalogyMappingEntry[];
  summary: string;
  /** Invariant: exactly one entry per id in the request's architecture[] (§2.2). */
  labelMappings: LabelMapping[];
}

export type AnalogyResponse = ApiResponse<AnalogyResult>;

/* ------------------------------------------------------------------ *
 * §2.3 — POST /api/crash-simulation
 * ------------------------------------------------------------------ */

export interface CrashSimulationRequest {
  /** Full node, not just an id — `evidence` grounds the narrative (RULES.md §6). */
  node: ArchitectureNode;
  analogyType: AnalogyType;
  /** The current theme's mapping[] entry for this node, when one exists (§2.3). */
  analogyMapping: AnalogyMappingEntry | null;
}

export interface CrashSimulationResult {
  /** ≤400 chars, truncated server-side at the last full sentence boundary (§2.3). */
  failureScenario: string;
}

export type CrashSimulationResponse = ApiResponse<CrashSimulationResult>;

/* ------------------------------------------------------------------ *
 * §4 — AnalysisPanel state (consumed by Phase 5.2's reducer)
 * ------------------------------------------------------------------ */

export type RequestStatus = "idle" | "loading" | "success" | "error";

export interface AnalogyState {
  status: RequestStatus;
  /** Currently selected theme — may differ from `data.analogyType` while a request is in flight. */
  type: AnalogyType | null;
  /** Last successful result; retained across a failed theme switch so the panel never blanks. */
  data: AnalogyResult | null;
}

export interface CrashState {
  status: RequestStatus;
  /** Most-recently-clicked node. Responses for any other id are discarded (last click wins, PRD.md §6). */
  pendingNodeId: string | null;
  /** Node the currently-rendered `result` belongs to; also the re-click-to-dismiss discriminator. */
  resultNodeId: string | null;
  result: CrashSimulationResult | null;
}

export interface AnalysisState {
  status: RequestStatus;
  repoSummary: RepoSummary | null;
  architecture: ArchitectureNode[];
  /**
   * The mermaid code on screen: the sanitized, repo-path-labelled string returned by /api/analyze.
   *
   * Set once per analysis and never rewritten. The former "Dynamic Diagram Label Morphing"
   * (ARCHITECTURE.md §5.1) that swapped these labels for analogy labels on ANALOGY_SUCCESS is
   * retired: the diagram now stays the repository's own structure, and a theme's mapping for a
   * folder is surfaced on hover instead (components/FlowchartView.tsx).
   */
  mermaidCode: string | null;
  /**
   * The same string as `mermaidCode`, held separately as the immutable, never-morphed baseline the
   * diagram was generated from. Kept so a future label-swapping mode has an untampered source to
   * rebuild from (ARCHITECTURE.md §5.1 point 1: always rebuild, never patch).
   */
  technicalMermaidCode: string | null;
  verdict: Verdict | null;
  /** Error surfaced by ErrorBanner via ERROR_MESSAGES; null when status is not "error". */
  error: ErrorCode | null;
  analogyState: AnalogyState;
  crashState: CrashState;
}

/** The 9 actions from ARCHITECTURE.md §4. CRASH_SIM_* may be stubbed until Phase 5.6b. */
export type AnalysisAction =
  | { type: "SUBMIT" }
  | {
      type: "ANALYZE_SUCCESS";
      payload: {
        repoSummary: RepoSummary;
        architecture: ArchitectureNode[];
        mermaidCode: string;
        verdict: Verdict | null;
      };
    }
  | { type: "ANALYZE_ERROR"; payload: { error: ErrorCode } }
  | { type: "ANALOGY_LOADING"; payload: { analogyType: AnalogyType } }
  | { type: "ANALOGY_SUCCESS"; payload: { data: AnalogyResult } }
  | { type: "ANALOGY_ERROR"; payload: { error: ErrorCode } }
  | { type: "CRASH_SIM_REQUEST"; payload: { nodeId: string } }
  | { type: "CRASH_SIM_SUCCESS"; payload: { nodeId: string; data: CrashSimulationResult } }
  | { type: "CRASH_SIM_ERROR"; payload: { nodeId: string; error: ErrorCode } };

export const INITIAL_ANALYSIS_STATE: AnalysisState = {
  status: "idle",
  repoSummary: null,
  architecture: [],
  mermaidCode: null,
  technicalMermaidCode: null,
  verdict: null,
  error: null,
  analogyState: { status: "idle", type: null, data: null },
  crashState: {
    status: "idle",
    pendingNodeId: null,
    resultNodeId: null,
    result: null,
  },
};
